/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as ToolsSampleSizeRouteImport } from './routes/tools.sample-size'
import { Route as ToolsNutritionRouteImport } from './routes/tools.nutrition'
import { Route as ToolsImnciRouteImport } from './routes/tools.imnci'
import { Route as ToolsGrowthRouteImport } from './routes/tools.growth'
import { Route as ToolsBmiRouteImport } from './routes/tools.bmi'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as FormsNewRouteImport } from './routes/forms.new'
import { Route as AnalyticsIdRouteImport } from './routes/analytics.$id'
import { Route as FormsIdFillRouteImport } from './routes/forms.$id.fill'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSampleSizeRoute = ToolsSampleSizeRouteImport.update({
  id: '/tools/sample-size',
  path: '/tools/sample-size',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNutritionRoute = ToolsNutritionRouteImport.update({
  id: '/tools/nutrition',
  path: '/tools/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImnciRoute = ToolsImnciRouteImport.update({
  id: '/tools/imnci',
  path: '/tools/imnci',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGrowthRoute = ToolsGrowthRouteImport.update({
  id: '/tools/growth',
  path: '/tools/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBmiRoute = ToolsBmiRouteImport.update({
  id: '/tools/bmi',
  path: '/tools/bmi',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIdRoute = AnalyticsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnalyticsRoute,
} as any)
const FormsIdFillRoute = FormsIdFillRouteImport.update({
  id: '/forms/$id/fill',
  path: '/forms/$id/fill',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/tools/bmi': typeof ToolsBmiRoute
  '/tools/growth': typeof ToolsGrowthRoute
  '/tools/imnci': typeof ToolsImnciRoute
  '/tools/nutrition': typeof ToolsNutritionRoute
  '/tools/sample-size': typeof ToolsSampleSizeRoute
  '/forms/': typeof FormsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/forms/$id/fill': typeof FormsIdFillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/tools/bmi': typeof ToolsBmiRoute
  '/tools/growth': typeof ToolsGrowthRoute
  '/tools/imnci': typeof ToolsImnciRoute
  '/tools/nutrition': typeof ToolsNutritionRoute
  '/tools/sample-size': typeof ToolsSampleSizeRoute
  '/forms': typeof FormsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/forms/$id/fill': typeof FormsIdFillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/analytics/$id': typeof AnalyticsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/tools/bmi': typeof ToolsBmiRoute
  '/tools/growth': typeof ToolsGrowthRoute
  '/tools/imnci': typeof ToolsImnciRoute
  '/tools/nutrition': typeof ToolsNutritionRoute
  '/tools/sample-size': typeof ToolsSampleSizeRoute
  '/forms/': typeof FormsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/forms/$id/fill': typeof FormsIdFillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/settings'
    | '/analytics/$id'
    | '/forms/new'
    | '/patients/$id'
    | '/patients/new'
    | '/tools/bmi'
    | '/tools/growth'
    | '/tools/imnci'
    | '/tools/nutrition'
    | '/tools/sample-size'
    | '/forms/'
    | '/patients/'
    | '/tools/'
    | '/forms/$id/fill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/settings'
    | '/analytics/$id'
    | '/forms/new'
    | '/patients/$id'
    | '/patients/new'
    | '/tools/bmi'
    | '/tools/growth'
    | '/tools/imnci'
    | '/tools/nutrition'
    | '/tools/sample-size'
    | '/forms'
    | '/patients'
    | '/tools'
    | '/forms/$id/fill'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/settings'
    | '/analytics/$id'
    | '/forms/new'
    | '/patients/$id'
    | '/patients/new'
    | '/tools/bmi'
    | '/tools/growth'
    | '/tools/imnci'
    | '/tools/nutrition'
    | '/tools/sample-size'
    | '/forms/'
    | '/patients/'
    | '/tools/'
    | '/forms/$id/fill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  FormsNewRoute: typeof FormsNewRoute
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  ToolsBmiRoute: typeof ToolsBmiRoute
  ToolsGrowthRoute: typeof ToolsGrowthRoute
  ToolsImnciRoute: typeof ToolsImnciRoute
  ToolsNutritionRoute: typeof ToolsNutritionRoute
  ToolsSampleSizeRoute: typeof ToolsSampleSizeRoute
  FormsIndexRoute: typeof FormsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  FormsIdFillRoute: typeof FormsIdFillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sample-size': {
      id: '/tools/sample-size'
      path: '/tools/sample-size'
      fullPath: '/tools/sample-size'
      preLoaderRoute: typeof ToolsSampleSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/nutrition': {
      id: '/tools/nutrition'
      path: '/tools/nutrition'
      fullPath: '/tools/nutrition'
      preLoaderRoute: typeof ToolsNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/imnci': {
      id: '/tools/imnci'
      path: '/tools/imnci'
      fullPath: '/tools/imnci'
      preLoaderRoute: typeof ToolsImnciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/growth': {
      id: '/tools/growth'
      path: '/tools/growth'
      fullPath: '/tools/growth'
      preLoaderRoute: typeof ToolsGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bmi': {
      id: '/tools/bmi'
      path: '/tools/bmi'
      fullPath: '/tools/bmi'
      preLoaderRoute: typeof ToolsBmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/$id': {
      id: '/analytics/$id'
      path: '/$id'
      fullPath: '/analytics/$id'
      preLoaderRoute: typeof AnalyticsIdRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/forms/$id/fill': {
      id: '/forms/$id/fill'
      path: '/forms/$id/fill'
      fullPath: '/forms/$id/fill'
      preLoaderRoute: typeof FormsIdFillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsIdRoute: typeof AnalyticsIdRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsIdRoute: AnalyticsIdRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  FormsNewRoute: FormsNewRoute,
  PatientsIdRoute: PatientsIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  ToolsBmiRoute: ToolsBmiRoute,
  ToolsGrowthRoute: ToolsGrowthRoute,
  ToolsImnciRoute: ToolsImnciRoute,
  ToolsNutritionRoute: ToolsNutritionRoute,
  ToolsSampleSizeRoute: ToolsSampleSizeRoute,
  FormsIndexRoute: FormsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  FormsIdFillRoute: FormsIdFillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
